// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbVA94YsANkxLY6oftau6-7rOipIGpTBc',
    appId: '1:353636819470:web:14f02993269d6bd31a925f',
    messagingSenderId: '353636819470',
    projectId: 'billingapp-a00e6',
    authDomain: 'billingapp-a00e6.firebaseapp.com',
    storageBucket: 'billingapp-a00e6.firebasestorage.app',
    measurementId: 'G-3DQTD2X3H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_7-fYMX0WrbzcYqUBBoHxeV-PtXxMdaM',
    appId: '1:353636819470:android:e855d641f721b1cf1a925f',
    messagingSenderId: '353636819470',
    projectId: 'billingapp-a00e6',
    storageBucket: 'billingapp-a00e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcvdAYjl9DZO_uyJgpKlv7YO5rVAAa22w',
    appId: '1:353636819470:ios:e64775d130aa130b1a925f',
    messagingSenderId: '353636819470',
    projectId: 'billingapp-a00e6',
    storageBucket: 'billingapp-a00e6.firebasestorage.app',
    iosBundleId: 'com.example.billingApp',
  );
}
